name: cube4health-binder
channels:
  - conda-forge

dependencies:
  # Python
  - python=3.10
  - pip

  # Essential geospatial stack (Binder-friendly)
  - gdal
  - rasterio
  - fiona
  - geopandas
  - shapely
  - pyproj
  - rioxarray

  # Scientific stack
  - numpy
  - pandas
  - matplotlib
  - xarray
  - tqdm

# Install cube4health after all dependencies are ready
postBuild: |
  pip install --no-deps git+https://github.com/Harmonize-Brazil/cube4health.git@main
