name: cube4health-binder
channels:
  - conda-forge

dependencies:
  # Core Python
  - python=3.11
  - pip

  # Geospatial stack (pinned for stability & size)
  - gdal=3.6.*
  - rasterio=1.3.*
  - fiona=1.9.*
  - geopandas
  - shapely
  - pyproj
  - rioxarray

  # Scientific stack
  - numpy
  - pandas
  - xarray
  - matplotlib
  - psutil
  - tqdm
  - netcdf4
  - h5py
  - pyarrow
  - fastparquet

  # Install cube4health from GitHub
  - pip:
      - git+https://github.com/Harmonize-Brazil/cube4health@main
