name: cube4health-binder
channels:
  - conda-forge

dependencies:
  # Core Python
  - python=3.10
  - pip

  # Geospatial stack (conda needed for GDAL binaries)
  - gdal
  - rasterio
  - fiona
  - geopandas
  - shapely
  - pyproj
  - rioxarray

  # Scientific stack
  - numpy
  - pandas
  - xarray
  - matplotlib
  - psutil
  - tqdm
  - netcdf4
  - h5py
  - pyarrow
  - fastparquet

  # Install cube4health directly from GitHub
  - pip:
      - git+https://github.com/Harmonize-Brazil/cube4health@main
